
create table if not exists cat_user (
                                        id varchar(64) not null,
                                        username varchar(255) default 'noname cat',
                                        nickname varchar(255)
);

create unique index user_id_uindex on "cat_user" (id);

create table if not exists cat_post (
                                        id int generated by default as identity primary key,
                                        author_id varchar(64) not null,
                                        description varchar(500),
                                        photo_url varchar(1000),
                                        creation_date timestamp,
                                        constraint fk_post_author foreign key(author_id) references cat_user(id)
);

insert into cat_user (id, username, nickname)
values
    ('gruphythegoat', 'Gruphy Maccheese', 'gruphyGG'),
    ('tom', 'Tom Nickson', 'tompson1337'),
    ('puss_in_boots', 'Peter Parker', 'spiderman2000');

insert into cat_post (author_id, description, photo_url, creation_date)
values ('gruphythegoat', 'my first post', 'https://test.ru/gruphy', '2023-12-21'),
       ('tom', 'my lovely cat', 'https://test.ru/tom', '2023-12-11'),
       ('puss_in_boots', 'haha say haha', 'https://test.ru/puss_in_boots', '2023-11-24');

create table cat_chat (
    id int generated by default as identity primary key,
    user_from varchar(255),
    user_to varchar(255),
    send_date timestamp,
    message varchar(1024),
    user_read boolean
);

create table cat_follow (
    author_id varchar,
    follower_id varchar
);